### ISSUE TITLE
Can't load syntax when remote has different name than package path name

### ISSUE THREAD

**Issue by michaelblyons** [SublimeText/syntax-test-action#1]
Is [this happening](https://github.com/michaelblyons/SublimeSyntax-HTML-CSharp/runs/781964851) because I need to change a setting somewhere? Or is the problem that my repo is named something different than the package name?

```
Linking package
'/syntax_tests/Data/Packages/SublimeSyntax-HTML-CSharp' -> '/github/workspace'
Running binary
Unable to init server: Could not connect: Connection refused
Error loading syntax file "Packages/HTML (C#)/ashx.sublime-syntax": Unable to read Packages/HTML (C#)/ashx.sublime-syntax
Error loading syntax file "Packages/HTML (C#)/aspnet.sublime-syntax": Unable to read Packages/HTML (C#)/aspnet.sublime-syntax
```

**Comment by FichteFoll** [comment]
Are you only talking about the "connection refused" line? I noticed that when I set this up, but it didn't actually affect anything, so I ignored it. It seems to be printed on every invocation but does not affect the results, since it passes for PackageDev and the tests within this repo work as well.

**Comment by michaelblyons** [comment]
Okay. I think more likely it's the latter problem, then.

I do not name my remotes the same as I do in my clones. (i.e. What does "michaelblyons/Packages" mean? so I name it "SublimeSyntax-Defaults" instead.) I think this is making problems when the workflow downloads to `/syntax_tests/Data/Packages/SublimeSyntax-HTML-CSharp` and then runs tests in a file that looks for `Packages/HTML (C#)/aspnet.sublime-syntax`.

Is there a way to configure the location one's package is downloaded to?

**Comment by FichteFoll** [comment]
> Is there a way to configure the location one's package is downloaded to?

Yes, this is what the `package_name` input is for.

**Comment by michaelblyons** [comment]
> Yes, this is what the `package_name` input is for.

Awesome! It works great now. I look forward to an additional option when HQ gets around to https://github.com/sublimehq/sublime_text/issues/3401 😉
