### ISSUE TITLE
Regex engine compatibility

### ISSUE THREAD

**Issue by HorlogeSkynet** [SublimeText/syntax-test-action#10]
Hey @FichteFoll ! First of all, thanks for this action.
I was wondering whether it could (optionally) run the "regex compatibility" syntax check. Is this even supported by the ST `syntax_tests` binary ?
Thanks for your time, feel free to close this if it's not possible. Bye 👋

**Comment by keith-hall** [comment]
This is currently not possible, see https://github.com/sublimehq/sublime_text/issues/3401 for the related feature request in the syntax_tests CLI runner.

**Comment by HorlogeSkynet** [comment]
Thanks for your answer @keith-hall, I'd be happy to propose a PR when it will be supported. Bye 👋
