### ISSUE TITLE
v2 is not available in Marketplace

### ISSUE THREAD

**Issue by jwortmann** [SublimeText/syntax-test-action#4]
Only v1 is listed: https://github.com/marketplace/actions/sublime-text-syntax-tests

**Comment by FichteFoll** [comment]
Thanks for the heads-up. It appears I had to accept the updated GitHub Marketplace Developer Agreement on behalf of the SublimeText org before I could publish the new version and I may also need to publish every tag manually through the website. Let's hope I won't forget for v3.
