### ISSUE TITLE
Runs for 3211 are being canceled out of nowhere

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/syntax-test-action#5]
No idea what's going on here currently. Creating an issue for tracking.

https://github.com/SublimeText/PackageDev/pull/310/checks?check_run_id=1297114279

**Comment by michaelblyons** [comment]
Is this not just "Hey, the other pipeline failed, so don't bother with this one" ?

**Comment by FichteFoll** [comment]
Yeah, I thought so too. Forgot I created an issue to check this later. Thanks for the heads-up.
