### ISSUE TITLE
latest is broken (used URL redirects to a 404)

### ISSUE THREAD

**Issue by willstott101** [SublimeText/syntax-test-action#9]
https://download.sublimetext.com/latest/dev/linux/x64/syntax_tests currently redirects to https://download.sublimetext.com/st3_syntax_tests_build_4106_x64.tar.bz2 which 404s

**Comment by willstott101** [comment]
FYI - I've just had to pin `3210` in my action to get it running again.

**Comment by FichteFoll** [comment]
Thanks for the notice, I forwarded the issue. 

However, I will need to update handling of `latest` afterwards, since I treat it as an ST3 build for dependency installation. Nothing big, though, as it's just unnecessary.

**Comment by FichteFoll** [comment]
The redirect has been fixed. I will update the action later today as I already made the changes and just need to push them and have CI pass.

**Comment by FichteFoll** [comment]
And done. v2 is aliased to the newly released v2.1.
